In [82]:
import torch

lbeta = 10.0
ubeta = 110.0
n_steps = 10


# SCHEDULE 1

In [12]:
beta = torch.linspace(lbeta, ubeta, n_steps + 1)

In [13]:
beta

tensor([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100., 110.])

# SCHEDULE 2

In [76]:
t_by_T_sq = (torch.arange(0,n_steps + 1)/(n_steps))**2

vec = lbeta + (ubeta - lbeta)*t_by_T_sq

In [77]:
vec

tensor([ 10.0000,  11.0000,  14.0000,  19.0000,  26.0000,  35.0000,  46.0000,
         59.0000,  74.0000,  91.0000, 110.0000])

# SCHEDULE 3

In [78]:
t_by_T_cube = (torch.arange(0,n_steps + 1)/(n_steps))**3

vec = lbeta + (ubeta - lbeta)*t_by_T_sq

In [79]:
vec

tensor([ 10.0000,  11.0000,  14.0000,  19.0000,  26.0000,  35.0000,  46.0000,
         59.0000,  74.0000,  91.0000, 110.0000])

# SCHEDULE 4

In [57]:
t_by_T = (torch.arange(0,n_steps + 1)/(n_steps))

In [58]:
exponent = t_by_T*torch.log(torch.tensor(ubeta/lbeta))

In [59]:
vec = lbeta*torch.exp(exponent)

In [60]:
vec

tensor([ 10.0000,  12.7098,  16.1539,  20.5314,  26.0950,  33.1662,  42.1537,
         53.5766,  68.0948,  86.5473, 110.0000])

# SCHEDULE 5

In [38]:
e = torch.exp(torch.tensor(1))

In [40]:
a = (torch.exp(torch.tensor(ubeta/lbeta)) - e)/n_steps

In [41]:
a

tensor(5987.1421)

In [43]:
t_range = torch.arange(0,n_steps + 1)

In [46]:
vec = lbeta*torch.log(a*t_range + e)

In [47]:
vec

tensor([ 10.0000,  86.9782,  93.9074,  97.9613, 100.8378, 103.0690, 104.8920,
        106.4334, 107.7687, 108.9464, 110.0000])

# SCHEDULE 6

In [ ]:
t_by_T = (torch.arange(0,n_steps + 1)/(n_steps))

In [65]:
vec = lbeta + (ubeta-lbeta)*torch.sin((torch.pi/2)*t_by_T)

In [66]:
vec

tensor([ 10.0000,  25.6434,  40.9017,  55.3991,  68.7785,  80.7107,  90.9017,
         99.1007, 105.1057, 108.7688, 110.0000])

In [ ]:
t_by_T = (torch.arange(0,n_steps + 1)/(n_steps))

In [80]:
vec = lbeta + (ubeta-lbeta)*torch.cos((torch.pi/2) - (torch.pi/2)*t_by_T)

In [81]:
vec

tensor([ 10.0000,  25.6434,  40.9017,  55.3991,  68.7785,  80.7107,  90.9017,
         99.1006, 105.1057, 108.7688, 110.0000])

# SCHEDULE 7

In [ ]:
t_by_T = (torch.arange(0,n_steps + 1)/(n_steps))

In [ ]:
vec = lbeta + (ubeta-lbeta)*t_by_T + torch.sin((torch.pi*16)*t_by_T)

In [ ]:
vec